#!/bin/sh

###
CONFIG_FILE=".var/app/io.github.ec_.Quake3e.OpenArena/config/cfg"
# Check if the config file exists
if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
fi
# Check if it's the first run or if RESPECT_XDGDIRS is not set
if [ ! -f "$CONFIG_FILE" ] || [ -z "$RESPECT_XDGDIRS" ]; then
    RESPECT_XDGDIRS=0

    # Save RESPECT_XDGDIRS in the config file
    echo "RESPECT_XDGDIRS=$RESPECT_XDGDIRS" > "$CONFIG_FILE"
fi
# Use the value of RESPECT_XDGDIRS to determine the directory
if [ "$RESPECT_XDGDIRS" -eq 1 ]; then
    # Use ~/.var/app/io.github.ec_.Quake3e.OpenArena/.openarena/ directory
    mkdir -p "$HOME/.var/app/io.github.ec_.Quake3e.OpenArena/homepath"
    OA_DIR="$HOME/.var/app/io.github.ec_.Quake3e.OpenArena/homepath"
    rm -rf "$HOME/.openarena"
else
    # Use .openarena directory
    OA_DIR="$HOME/.openarena"
    mkdir -p "$HOME/.var/app/io.github.ec_.Quake3e.OpenArena/homepath"
fi
###

OA_CVARS="+set fs_basegame baseoa +set protocol 71 +set fs_homepath $OA_DIR"
DISABLED_CVARS="+set com_protocol 72 +set cl_voip 1"
arch="$(uname -m)"
case "$arch" in
    x86_64) q3e_arch="x64" ;;
    aarch64) q3e_arch="aarch64" ;;
esac

if [ "$RESPECT_CONVENTIONS" -eq 0 ]; then
    echo -e "If you'd rather change your homepath from ~/.openarena to ~/.var/app/io.github.ec_.Quake3e.OpenArena/homepath you can set the variable RESPECT_CONVENTIONS to 1 in the following config file: ~/.var/app/io.github.ec_.Quake3e.OpenArena/config/cfg \n"
fi

if [ "$Q3ENGINE" != "" ]; then
    if [ "$CVARS" != "" ]; then
        exec ${Q3ENGINE} "$CVARS" "$@"
        CVARS=""
        Q3ENGINE=""
    else
        echo "Change CVARS variable before starting in order to change basegame or other game variables. In order to add CVARS to OA, just add them as arguments."
        exec ${Q3ENGINE} "$OA_CVARS" "$@"
        Q3ENGINE=""
    fi
else
    if [ "$CVARS" != "" ]; then
        exec /app/share/openarena/quake3e.${q3e_arch} "$CVARS" "$@"
        CVARS=""
    else
        echo -e "Change CVARS variable before starting in order to change basegame. In order to add CVARS to OA, just add them as arguments. \n"
        exec /app/share/openarena/quake3e.${q3e_arch} "$OA_CVARS" "$@"
    fi
fi
